package jsval_test

import "github.com/lestrrat/go-jsval"

func JSValFoo() *jsval.JSVal {
	V := jsval.New()
	V.SetRoot(
		jsval.Object().
			AdditionalProperties(
				jsval.NilConstraint,
			).
			AddProp(
				`default`,
				jsval.Object().
					AdditionalProperties(
						jsval.NilConstraint,
					),
			).
			AddProp(
				`pattern`,
				jsval.String(),
			).
			AddProp(
				`title`,
				jsval.String(),
			).
			AddProp(
				`enum`,
				jsval.Array().MinItems(1).MaxItems(0).UniqueItems(),
			).
			AddProp(
				`multipleOf`,
				jsval.Number().Minimum(0.000000).ExclusiveMinimum(true),
			).
			AddProp(
				`minItems`,
				jsval.Reference(V).RefersTo(`#/definitions/positiveIntegerDefault0`),
			).
			AddProp(
				`oneOf`,
				jsval.Reference(V).RefersTo(`#/definitions/schemaArray`),
			).
			AddProp(
				`not`,
				jsval.Reference(V).RefersTo(`#`),
			).
			AddProp(
				`$schema`,
				jsval.String(),
			).
			AddProp(
				`minimum`,
				jsval.Number(),
			).
			AddProp(
				`additionalItems`,
				jsval.All().
					Add(
						jsval.Any().
							Add(
								jsval.Boolean(),
							).
							Add(
								jsval.Reference(V).RefersTo(`#`),
							),
					).
					Add(
						jsval.Object().
							AdditionalProperties(
								jsval.NilConstraint,
							),
					),
			).
			AddProp(
				`uniqueItems`,
				jsval.Boolean(),
			).
			AddProp(
				`minProperties`,
				jsval.Reference(V).RefersTo(`#/definitions/positiveIntegerDefault0`),
			).
			AddProp(
				`patternProperties`,
				jsval.Object().
					AdditionalProperties(
						jsval.Reference(V).RefersTo(`#`),
					),
			).
			AddProp(
				`maxLength`,
				jsval.Reference(V).RefersTo(`#/definitions/positiveInteger`),
			).
			AddProp(
				`required`,
				jsval.Reference(V).RefersTo(`#/definitions/stringArray`),
			).
			AddProp(
				`anyOf`,
				jsval.Reference(V).RefersTo(`#/definitions/schemaArray`),
			).
			AddProp(
				`dependencies`,
				jsval.Object().
					AdditionalProperties(
						jsval.All().
							Add(
								jsval.Any().
									Add(
										jsval.Reference(V).RefersTo(`#`),
									).
									Add(
										jsval.Reference(V).RefersTo(`#/definitions/stringArray`),
									),
							).
							Add(
								jsval.Object().
									AdditionalProperties(
										jsval.NilConstraint,
									),
							),
					),
			).
			AddProp(
				`maxItems`,
				jsval.Reference(V).RefersTo(`#/definitions/positiveInteger`),
			).
			AddProp(
				`type`,
				jsval.All().
					Add(
						jsval.Any().
							Add(
								jsval.Reference(V).RefersTo(`#/definitions/simpleTypes`),
							).
							Add(
								jsval.Array().MinItems(1).MaxItems(0).UniqueItems(),
							),
					).
					Add(
						jsval.Object().
							AdditionalProperties(
								jsval.NilConstraint,
							),
					),
			).
			AddProp(
				`properties`,
				jsval.Object().
					AdditionalProperties(
						jsval.Reference(V).RefersTo(`#`),
					),
			).
			AddProp(
				`exclusiveMaximum`,
				jsval.Boolean(),
			).
			AddProp(
				`description`,
				jsval.String(),
			).
			AddProp(
				`items`,
				jsval.All().
					Add(
						jsval.Any().
							Add(
								jsval.Reference(V).RefersTo(`#`),
							).
							Add(
								jsval.Reference(V).RefersTo(`#/definitions/schemaArray`),
							),
					).
					Add(
						jsval.Object().
							AdditionalProperties(
								jsval.NilConstraint,
							),
					),
			).
			AddProp(
				`allOf`,
				jsval.Reference(V).RefersTo(`#/definitions/schemaArray`),
			).
			AddProp(
				`exclusiveMinimum`,
				jsval.Boolean(),
			).
			AddProp(
				`maxProperties`,
				jsval.Reference(V).RefersTo(`#/definitions/positiveInteger`),
			).
			AddProp(
				`maximum`,
				jsval.Number(),
			).
			AddProp(
				`minLength`,
				jsval.Reference(V).RefersTo(`#/definitions/positiveIntegerDefault0`),
			).
			AddProp(
				`additionalProperties`,
				jsval.All().
					Add(
						jsval.Any().
							Add(
								jsval.Boolean(),
							).
							Add(
								jsval.Reference(V).RefersTo(`#`),
							),
					).
					Add(
						jsval.Object().
							AdditionalProperties(
								jsval.NilConstraint,
							),
					),
			).
			AddProp(
				`definitions`,
				jsval.Object().
					AdditionalProperties(
						jsval.Reference(V).RefersTo(`#`),
					),
			).
			AddProp(
				`id`,
				jsval.String(),
			),
	)

	V.SetReference(
		`#`,
		V.Root(),
	)
	V.SetReference(
		`#/definitions/schemaArray`,
		jsval.Array().MinItems(1).MaxItems(0),
	)
	V.SetReference(
		`#/definitions/positiveInteger`,
		jsval.Integer().Minimum(0),
	)
	V.SetReference(
		`#/definitions/simpleTypes`,
		jsval.String().Enum([]interface{}{"array", "boolean", "integer", "null", "number", "object", "string"}),
	)
	V.SetReference(
		`#/definitions/positiveIntegerDefault0`,
		jsval.All().
			Add(
				jsval.All().
					Add(
						jsval.Reference(V).RefersTo(`#/definitions/positiveInteger`),
					).
					Add(
						jsval.Object().
							AdditionalProperties(
								jsval.NilConstraint,
							),
					),
			).
			Add(
				jsval.Object().
					AdditionalProperties(
						jsval.NilConstraint,
					),
			),
	)
	V.SetReference(
		`#/definitions/stringArray`,
		jsval.Array().MinItems(1).MaxItems(0).UniqueItems(),
	)
	return V
}
